### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'tuning_mode'

### ISSUE THREAD

**Issue by LOVEISI** [salesforce/CodeRL#61]
Traceback (most recent call last):
  File "G:\CodeRL_A3\CodeRL\CodeRL\train.py", line 155, in <module>
    main(args)
  File "G:\CodeRL_A3\CodeRL\CodeRL\train.py", line 149, in main
    run_training(args, train_data)
  File "G:\CodeRL_A3\CodeRL\CodeRL\train.py", line 35, in run_training
    model = transformers.T5ForConditionalGeneration.from_pretrained(
  File "H:\Anaconda\envs\CodeRL_A3\lib\site-packages\transformers\modeling_utils.py", line 1489, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
TypeError: __init__() got an unexpected keyword argument 'tuning_mode'

When I run "$ /bin/bash scripts/train_critic.sh",it went wrong.
![image](https://github.com/user-attachments/assets/3c2e2a05-ca41-40b4-a88b-ee6fcccff22e)
![image](https://github.com/user-attachments/assets/1df75491-6599-4cdf-970a-af64df5d2ec4)

**Comment by YTJY** [comment]
Hello, I don't know if you solved this problem, I'm also experiencing this problem now, can you give me some advice

**Comment by LOVEISI** [comment]
> Hello, I don't know if you solved this problem, I'm also experiencing this problem now, can you give me some advice

![image](https://github.com/user-attachments/assets/4268f5c0-3f7b-4f01-bcb6-37b90cae7540)
I'm just going to simply remove this parameter now, like in the picture. But I don't know if anything will go wrong in the future.

**Comment by oshindow** [comment]
> > Hello, I don't know if you solved this problem, I'm also experiencing this problem now, can you give me some advice
> 
> ![image](https://github.com/user-attachments/assets/4268f5c0-3f7b-4f01-bcb6-37b90cae7540) I'm just going to simply remove this parameter now, like in the picture. But I don't know if anything will go wrong in the future.

Hi, what version of the transformers package did you use?

**Comment by LOVEISI** [comment]
Hi, transformers&nbsp; &nbsp; 4.51.3&nbsp; &nbsp; or&nbsp; 4.16.1 , I forget which one I used.But it must be one of the two visions.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "salesforce/CodeRL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年10月23日(星期四) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [salesforce/CodeRL] TypeError: __init__() got an unexpected keyword argument 'tuning_mode' (Issue #61)



oshindow left a comment (salesforce/CodeRL#61)
   
Hello, I don't know if you solved this problem, I'm also experiencing this problem now, can you give me some advice
  
image.png (view on web) I'm just going to simply remove this parameter now, like in the picture. But I don't know if anything will go wrong in the future.
  
Hi, what version of the transformers package did you use?
